/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                code: string;
                message: string;
                requestId?: string;
            };
        };
        APIResponse: {
            /** @description HTTP status code of the response. */
            status: number;
            /** @description Short human-readable summary of the operation's result. */
            summary: string;
            /** @description Correlation id; matches the x-request-id response header. */
            requestId?: string;
            /** @description Operation payload; shape is endpoint-specific. */
            data?: unknown;
        };
        Pagination: {
            page: number;
            perPage: number;
            total: number;
            totalPages: number;
            next?: number | null;
            prev?: number | null;
        };
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
            uptime: number;
            /** Format: date-time */
            timestamp: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIResponse"] & {
                        data: components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
    };
}
